plugins { id 'com.android.application' }

android {
    namespace 'com.tracker.professional'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tracker.professional'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.9.1'
}
